GET http://localhost:4001/postLogin/F0DF3v3r/test


#GET http://localhost:4001/preLogin/natalie.m.kendrick@gmail.com

# //POST http://localhost:4001/preLogin/testPassword
# Content-Type: : application/json

# {
#   "password": "davidBowie"
# }