//GET http://localhost:4001/preLogin/natalie.m.kendrick

#GET http://localhost:4001/postLogin/F00DF3v3r/test


#GET http://localhost:4001/preLogin/natalie.m.kendrick@gmail.com
PUT http://localhost:4001/preLogin/password/natalie.m.kendrick@gmail.com
Content-Type: : application/json

{
  "password": "davidBowie"
}
