export const DRAWER_STATE = 'DRAWER_STATE'

export const CREATE_NEW_USER = 'CREATE_NEW_USER'
export const LOGIN = 'LOGIN' 
export const LOGOUT = 'LOGOUT'
export const USER_DETAILS = 'USER_DETAILS'

export const YOUR_SHOPPING_LIST = 'YOUR_SHOPPING_LIST'
export const UPDATE_ITEM_ON_SHOPPING_LIST =   'UPDATE_ITEM_ON_SHOPPING_LIST'
export const REMOVE_FROM_SHOPPING_LIST =   'REMOVE_FROM_SHOPPING_LIST'
export const ADD_ITEM_TO_SHOPPING_LIST =   'ADD_ITEM_TO_SHOPPING_LIST'

export const FIND_FOOD = 'FIND_FOOD'
export const OPEN_FOOD_FINDER = 'OPEN_FOOD_FINDER'
export const RESET_FOOD_SEARCH = 'RESET_FOOD_SEARCH'
export const RESET_NEW_USER = 'RESET_NEW_USER'
